name: Add label to PR open for 3 days
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: add-label
        uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-label: "3days opened"
          days-before-pr-stale: 1 # [TODO] fix
          days-before-pr-close: -1